#!/bin/bash

if [ $# -eq 1 ]
then
    echo '######## cd src ########'
    cd src
    echo '######## ng build ########'
    ng build --watch &
    echo '######## cd .. ########'
    cd ..
fi
echo '######## startup server ########'
sudo PGPASSFILE=.pgpass \
    node server.js
